if: branch != master AND type = push
language: node_js
node_js:
    - 12.16.2
install:
    - yarn bootstrap
script:
    - cd frontend/
    - yarn test
    - yarn lint
    - yarn build
cache:
    yarn: true
    directories:
        - node_modules
notifications:
    email: false
