import { Theme } from './types'
import { THEME } from '@worldbrain/memex-common/lib/common-ui/styles/theme'

export const theme: Theme = THEME({
    icons: {
        comment: require('../../assets/img/comment.svg'),
        commentFull: require('../../assets/img/comment.svg'),
        commentEmpty: require('../../assets/img/comment-empty.svg'),
        goTo: require('../../assets/img/open.svg'),
        lock: require('../../assets/img/lock.svg'),
        person: require('../../assets/img/person.svg'),
        plus: require('../../assets/img/plus.svg'),
        shareEmpty: require('../../assets/img/shareEmpty.svg'),
        shared: require('../../assets/img/shared.svg'),
        triangle: require('../../assets/img/triangleSmall.svg'),
        copy: require('../../assets/img/copy.svg'),
        removeX: require('../../assets/img/removeX.svg'),
        hamburger: require('../../assets/img/hamburger.svg'),
        addPeople: require('../../assets/img/addPeople.svg'),
        checkRound: require('../../assets/img/checkRound.svg'),
        check: require('../../assets/img/check.svg'),
        people: require('../../assets/img/people.svg'),
        plusIcon: require('../../assets/img/plusIcon.svg'),
        alertRound: require('../../assets/img/alertRound.svg'),
        webLogo: require('../../assets/img/web-logo.svg'),
        mediumLogo: require('../../assets/img/medium-logo.svg'),
        twitterLogo: require('../../assets/img/twitter-logo.svg'),
        youtubeLogo: require('../../assets/img/youtube-logo.svg'),
        spotifyLogo: require('../../assets/img/spotify-logo.svg'),
        substackLogo: require('../../assets/img/substack-logo.svg'),
        webMonetizationLogo: require('../../assets/img/web-monetization-logo.svg'),
        webMonetizationLogoConfirmed: require('../../assets/img/web-monetization-logo-confirmed.svg'),
        heartEmpty: require('../../assets/img/star_empty.svg'),
        personFine: require('../../assets/img/personFine.svg'),
        peopleFine: require('../../assets/img/peopleFine.svg'),
        settings: require('../../assets/img/settings.svg'),
        atSign: require('../../assets/img/atSign.svg'),
        multiEdit: require('../../assets/img/multiedit.svg'),
        close: require('../../assets/img/close.svg'),
        file: require('../../assets/img/file.svg'),
        fileFull: require('../../assets/img/fileFull.svg'),
        tagFull: require('../../assets/img/tag_full.svg'),
        tagEmpty: require('../../assets/img/tag_empty.svg'),
        filterIcon: require('../../assets/img/filterIcon.svg'),
        date: require('../../assets/img/date.svg'),
        globe: require('../../assets/img/globe.svg'),
        heartFull: require('../../assets/img/star_full.svg'),
        dropImage: require('../../assets/img/dropImage.svg'),
        phone: require('../../assets/img/phone.svg'),
        helpIcon: require('../../assets/img/help.svg'),
        searchIcon: require('../../assets/img/search.svg'),
        commentAdd: require('../../assets/img/comment_add.svg'),
        commentEdit: require('../../assets/img/comment_edit.svg'),
        compress: require('../../assets/img/compress-alt.svg'),
        expand: require('../../assets/img/expand-alt.svg'),
        play: require('../../assets/img/play.svg'),
        playFull: require('../../assets/img/playFull.svg'),
        pause: require('../../assets/img/pause.svg'),
        stop: require('../../assets/img/stop.svg'),
        warning: require('../../assets/img/warning_red.svg'),
        integrate: require('../../assets/img/integrate.svg'),
        noNote: require('../../assets/img/noNote.svg'),
        lockFine: require('../../assets/img/lockFine.svg'),
        mail: require('../../assets/img/mail.svg'),
        inbox: require('../../assets/img/inbox.svg'),
        sadFace: require('../../assets/img/sadFace.svg'),
        command: require('../../assets/img/command.svg'),
        clock: require('../../assets/img/clock.svg'),
        sunrise: require('../../assets/img/sunrise.svg'),
        folder: require('../../assets/img/folder.svg'),
        dots: require('../../assets/img/3dots.svg'),
        imports: require('../../assets/img/import.svg'),
        trash: require('../../assets/img/trash.svg'),
        sidebarIcon: require('../../assets/img/sidebarOn.svg'),
        edit: require('../../assets/img/edit.svg'),
        redo: require('../../assets/img/redo.svg'),
        shield: require('../../assets/img/shield.svg'),
        smileFace: require('../../assets/img/smileFace.svg'),
        login: require('../../assets/img/login.svg'),
        logout: require('../../assets/img/logout.svg'),
        pdf: require('../../assets/img/file-pdf.svg'),
        reload: require('../../assets/img/reload.svg'),
        link: require('../../assets/img/link.svg'),
        coilIcon: require('../../assets/img/coil-icon.svg'),
        threadIcon: require('../../assets/img/thread.svg'),
        checkedRound: require('../../assets/img/checkedRound.svg'),
        newFeed: require('../../assets/img/newFeed.svg'),
        bell: require('../../assets/img/bell.svg'),
        arrowDown: require('../../assets/img/arrowDown.svg'),

        // doubleArrow: require('../../assets/img/doubleArrow.svg'),
        // import tagFull from '../../assets/img/tag_full.svg'
        // import tagEmpty from '../../assets/img/tag_empty.svg'
        // import heartFull from '../../assets/img/heart_full.svg'
        // import heartEmpty from '../../assets/img/heart_empty.svg'
    },
    // colors: {
    //     background: 'white',
    //     warning: '#ff9090',
    //     primary: '#3a2f45',
    //     subText: '#aeaeae',
    //     purple: '#347AE2',
    //     white: '#fff',
    //     lightgrey: '#f0f0f0',
    //     darkgrey: '#545454',
    //     secondary: '#5cd9a6',
    //     grey: '#e0e0e0',
    //     black: '#000',
    //     overlay: {
    //         background: 'rgba(0, 0, 0, 0.1)',
    //         dialog: 'white',
    //     },
    //     lightblack: '#292C38',
    //     lineGrey: '#ECEFF4',
    //     lineLightGrey: '#E0E5ED',
    //     iconColor: '#96A0B5',
    //     darkerIconColor: '#7d8598',
    //     lightHover: '#F4F9FF',
    //     backgroundHighlight: '#e6f1ff',
    //     darkhover: '#E5F0FF',
    //     normalText: '#73778B',
    //     darkerText: '#292C38',
    //     lighterText: '#96A0B5',
    //     backgroundColor: '#F8FBFF',
    //     backgroundColorDarker: '#e5f0ff70',
    //     darkerBlue: '#5E6278',
    //     blue: '2563EB',
    // },
})
